version: '3'

# To use this create a ./data directory containing the registration and config.yml

services:
  mx-puppet-voipms:
    image: wildeyedskies/mx-puppet-voipms:latest
    restart: unless-stopped
    environment:
      - CONFIG_PATH=/data/config.yaml
      - REGISTRATION_PATH=/data/voipms-registration.yaml
    volumes:
      - ./data:/data

